### ISSUE TITLE
Investigate Metadata network-config

### ISSUE THREAD

**Issue by luthermonson** [linode/cluster-api-provider-linode#1]
There is some limited functionality to how MDS uses network config and we should investigate which features we may be missing from capi/cni/etc. if we solely rely on the MDS.

- Do we need to disable network helpers?

Possible good reading: https://www.linode.com/docs/products/compute/compute-instances/guides/metadata/?tabs=linode-api

**Comment by eljohnson92** [comment]
the default cluster template is now using metadata correctly, closing this out
