### ISSUE TITLE
e2e: Replace Kuttl-in-Kuttl with simple kubectl apply in scripts

### ISSUE THREAD

**Issue by bcm820** [linode/cluster-api-provider-linode#103]
The Kuttl-in-Kuttl pattern introduced in https://github.com/linode/cluster-api-provider-linode/pull/80 can be replaced with defining a script that simply runs `kubectl apply` while passing dynamic data. The `TestStep` will fail if any of the commands exit with non-zero.

```sh
MACHINE_UID="$(OBJ=machines/machine-sample make getKubeUid)"

cat <<EOF | kubectl apply -n $NAMESPACE -f -
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: LinodeMachine
metadata:
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: Machine
    name: machine-sample
    uid: ${MACHINE_UID}
EOF
```

**Comment by eddycharly** [comment]
One proposed solution is to switch to chainsaw that can do resource templating (WIP PR https://github.com/linode/cluster-api-provider-linode/pull/119).

See https://kyverno.io/blog/2024/02/15/kyverno-chainsaw-0.1.4-awesome-new-features/
