### ISSUE TITLE
400 error from Linode when provisioning a node

### ISSUE THREAD

**Issue by audrey-mux** [linode/cluster-api-provider-linode#198]
## General:

When creating a new node via the provider, the node never becomes ready. 

```
2024-03-14T21:59:25Z	ERROR	Reconciler error	{"controller": "linodemachine", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "LinodeMachine", "LinodeMachine": {"name":"control-plane-g6-standard-2-20240311-2-wp2dm","namespace":"infra"}, "namespace": "infra", "name": "control-plane-g6-standard-2-20240311-2-wp2dm", "reconcileID": "3ed72047-cff8-4a4c-a08b-145e21ee2414", "error": "[400] Disk size must be at least 1 MB"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227
```

Node is using the image `linode/fedora37` with a 80GB disk provisioned.

### Expected Behavior
Provisioned node becomes ready and is usable

### Actual Behavior
Node is running, but due to error never becomes `ready`

### Steps to Reproduce the Problem

  1.  Create a new LinodeMachine by creating or updating the LinodeMachineTemplate

#### Additional Notes

----

For general help or discussion, join the [Kubernetes Slack team](https://kubernetes.slack.com/messages/CD4B15LUR/details/) channel `#linode`. To sign up, use the [Kubernetes Slack inviter](http://slack.kubernetes.io/).

The [Linode Community](https://www.linode.com/community/questions/) is a great place to get additional support.

**Comment by audrey-mux** [comment]
Additional log 

2024-03-16T00:29:32Z	ERROR	LinodeMachineReconciler	Failed to resize root disk	{"controller": "linodemachine", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "LinodeMachine", "LinodeMachine": {"name":"control-plane-g6-standard-2-20240311-2-k24p2","namespace":"infra"}, "namespace": "linfra", "name": "control-plane-g6-standard-2-20240311-2-k24p2", "reconcileID": "fc7f9e53-39c8-4680-8d98-8bac8a38ba1a", "name": "infra/control-plane-g6-standard-2-20240311-2-k24p2", "LinodeMachine": "lin-us-sea-vos1-control-plane-lxz69", "error": "[400] Disk size must be at least 1 MB"}
github.com/linode/cluster-api-provider-linode/controller.(*LinodeMachineReconciler).configureDisksControlPlane
	/workspace/controller/linodemachine_controller.go:337
github.com/linode/cluster-api-provider-linode/controller.(*LinodeMachineReconciler).reconcileCreate
	/workspace/controller/linodemachine_controller.go:278
github.com/linode/cluster-api-provider-linode/controller.(*LinodeMachineReconciler).reconcile
	/workspace/controller/linodemachine_controller.go:232
github.com/linode/cluster-api-provider-linode/controller.(*LinodeMachineReconciler).Reconcile
	/workspace/controller/linodemachine_controller.go:140
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227

**Comment by eljohnson92** [comment]
hello @audrey-mux can you elaborate a bit on how you got this? were you only using the default template with `clusterctl` or were you hand rolling some config to deploy? I'd like to make sure I have all of the information to reproduce this

**Comment by eljohnson92** [comment]
Thanks for reporting, we will take a look and see if we can get a fix in for this
