### ISSUE TITLE
Investigate re-use of Crossplane provider

### ISSUE THREAD

**Issue by mhmxs** [linode/cluster-api-provider-linode#22]
I think there are lots of common parts with: https://github.com/linode/provider-linode. Would be nice to reuse implementations

**Comment by mhmxs** [comment]
As i understand crossplane provider uses terraform in the background. So i headed to terraform-linode-provider https://github.com/linode/terraform-provider-linode/blob/dev/docs/data-sources/instances.md. @luthermonson WDYT. Should we use terraform in the infrastructure layer?

**Comment by srust** [comment]
@luthermonson can correct me if I'm wrong, but I believe the most typical / straightforward path here is to use https://github.com/linode/linodego directly for the API calls necessary when interacting with Linode. The crossplane provider uses terraform because all of that code was generated, and that was the easiest path. The longer term plan for the https://github.com/linode/provider-linode is NOT to use terraform, and to not use generated code. The terraform abstraction is a bit of a performance hit and maintenance burden tbh.

**Comment by mhmxs** [comment]
> directly for the API calls necessary when interacting with Linode

@luthermonson It makes sense. I don't have experience with the library, but it looks low level. So as i see we should need some business logic for validating, creating, waiting, other extras. Because CAPI and Crossplane providers would need the same functionality, does it make sense to create a library to reuse most of the parts? I mean both CAPI and Crossplane providers should be a thin representation layer on top of this library.

**Comment by srust** [comment]
FWIW the Linode Crossplane provider must support every API endpoint similar to Terraform, and includes generated Go code based on the Terraform for this reason, and also for time to market.

Ideally, the crossplane provider would be re-written to use Linodego directly, however this also increases a maintenance burden on the Crossplane provider for having to keep the APIs up to date for any API change. By leveraging the Terraform generated code, the API code is updated in the Terraform provider, and then the Crossplane provider can just be generated based on that.

In the case of CAPI, we are using a subset of the Linode API, and merely are a consumer of the API, very similar to how https://github.com/linode/linode-blockstorage-csi-driver uses Linodego or how https://github.com/linode/linode-cloud-controller-manager/ uses Linodego to call the API.

I'm not sure what else is needed in a library besides https://github.com/linode/linodego itself and just using that.

What did you have in mind?

**Comment by mhmxs** [comment]
> What did you have in mind?

Thank you, it is clear now. I have very limited understanding, so i'm just thinking loudly about how to avoid any code duplication. From the high level of view, both providers are custom resource to linode service converters. And one is a subset of the other.
