### ISSUE TITLE
Tutorial setup does not work, requires version, specifying version also does not work

### ISSUE THREAD

**Issue by spacez320** [linode/cluster-api-provider-linode#380]
## General:

* [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x] Have you checked to ensure there aren't other open or closed [Pull Requests](https://github.com/linode/cluster-api-provider-linode/pulls) for the same bug/feature/question?

----

## Bug Reporting

```
# Trying with a version.
$ clusterctl generate cluster capi-quickstart --flavor development --kubernetes-version v1.30.0 --control-plane-machine-count=1 --worker-machine-count=1 --infrastructure linode-linode:v0.4.0

Error: failed to read "cluster-template-development.yaml" from provider's repository "infrastructure-linode-linode": failed to download files from GitHub release v0.4.0: failed to get file "cluster-template-development.yaml" from "v0.4.0" release

# Trying without a version, ala https://linode.github.io/cluster-api-provider-linode/topics/flavors/default.html.
$ clusterctl generate cluster capi-quickstart --flavor development --kubernetes-version v1.30.0 --control-plane-machine-count=1 --worker-machine-count=1 --infrastructure linode-linode

Error: Unable to identify version for the provider "linode-linode" automatically. Please specify a version
```

### Expected Behavior

More workingness.

### Actual Behavior

See above.

### Steps to Reproduce the Problem

  1. Download latest clusterctl utility.
  1. Configure Linode environment variables necessary to use it as an infrastructure provider.
  1. Attempt to run the commands above.

### Environment Specifications

```
$ uname -r
6.8.7-300.fc40.x86_64

$ cat /etc/fedora-release
Fedora release 40 (Forty)

$ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"b0284d8b9bf1220b744e8cfbfc812321c733e2dd", GitTreeState:"clean", BuildDate:"2024-06-11T10:14:56Z", GoVersion:"go1.21.11", Compiler:"gc", Platform:"linux/amd64"}
```

#### Screenshots, Code Blocks, and Logs

n/a

#### Additional Notes

Sorry if I'm missing something!

**Comment by spacez320** [comment]
Also happy to contribute some adjustment or fix to the provider, if there is a need.

**Comment by eljohnson92** [comment]
Hello @spacez320 it looks like there are two issues with our docs I will open up a pr to fix asap
One, part of our readme is poorly formatted and hard to read for initializing this provider
```
clusterctl init --infrastructure linode-linode --addon helm
```

If you run that command you should be able to then run this without the flavor spec(the second issue is `development` is not a valid flavor)
````
clusterctl generate cluster capi-quickstart --kubernetes-version v1.30.0 --control-plane-machine-count=1 --worker-machine-count=1 --infrastructure linode-linode
```

If you run these two commands does that get things working for you?

**Comment by spacez320** [comment]
@eljohnson92 I appreciate the guidance and documentation. The commands do work better, I didn't realize that the flavor option was getting in the way, sorry for not digging in further myself.

**Comment by eljohnson92** [comment]
Glad we could help! Feel free to open another issue if you run into anything else
