### ISSUE TITLE
Investigate Upstream Documentation

### ISSUE THREAD

**Issue by luthermonson** [linode/cluster-api-provider-linode#5]
Figure out where we need to update the docs in kube sig to get the linode bits added to https://cluster-api.sigs.k8s.io/

**Comment by eljohnson92** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/9798/files#diff-9fedf90d443f8d1e1e2c606470cb37e9b684f79c1cd49507990cf2a3421d4bc1 this PR shows an example of how we can contribute our provider once we are ready

**Comment by eljohnson92** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/10471 has been opened to handle this

**Comment by eljohnson92** [comment]
documentation has been added for the `linode-linode` provider in the cluster-api repo/docs page
