### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by luthermonson** [linode/cluster-api-provider-linode#7]
- e2e with a linode token... find out how we can get a capi testing account?
- Mocks? Look into how CAPA was mocking kube api and aws api calls
- ginkgo?

**Comment by mhmxs** [comment]
@luthermonson may i suggest to use https://kuttl.dev/ to provision Kubernetes and execute e2e (or other tests which fits into) tests? We have good experiences with it, and is is simple as possible.

**Comment by luthermonson** [comment]
if you think itll help us get something that looks like e2e in both local and a gh action then let's give it a shot

**Comment by mhmxs** [comment]
@luthermonson here is a very basic test case in Kuttl (plus environment) https://github.com/linode/cluster-api-provider-linode/pull/62/commits/b0ce89799e56c743991cbced3c1f80352076b5b0
