### ISSUE TITLE
Investigate RKE2 Bootstrap Provider

### ISSUE THREAD

**Issue by luthermonson** [linode/cluster-api-provider-linode#8]
We might be able to use this for rke2 clusters: https://github.com/rancher-sandbox/cluster-api-provider-rke2

**Comment by mhmxs** [comment]
May i take this?

**Comment by mhmxs** [comment]
The provider uses https://www.flatcar.org/docs/latest/provisioning/ignition/ under the hood. Does it fit to our requirements?

**Comment by luthermonson** [comment]
of course you may have this! i think we should start with cloudinit and get that working first before we consider ignition, agree?

**Comment by mhmxs** [comment]
> we should start with cloudinit

You are right, i have found the code snippet:
```golang
switch scope.Config.Spec.AgentConfig.Format {
	case bootstrapv1.Ignition:
		userData, err = ignition.NewJoinControlPlane(&ignition.ControlPlaneInput{
			ControlPlaneInput:  cpinput,
			AdditionalIgnition: &scope.Config.Spec.AgentConfig.AdditionalUserData,
		})
	default:
		userData, err = cloudinit.NewJoinControlPlane(cpinput)
	}
```

**Comment by mhmxs** [comment]
Here is the bootstrap process of cluster api: https://cluster-api.sigs.k8s.io/developer/architecture/controllers/bootstrap

So this comment is theoretical, but bootstrap controller watches `RKE2Config` objects, generates a secret with the rendered `cloud-init`. `RKE2Config` is coming from `MachineDeployment` controller, it contains bootstrap config reference. This reference should be any kind. I case of RKE2 this kind is `RKE2ConfigTemplate`. As i understand now, `Machine` controller has to take care on running initialization script persisted in the secret. So if we have our custom `Machine` controller for Linode, I don't see any issue within re-using the bootstrap controller as it is (without modification).

**Comment by luthermonson** [comment]
sorry, didnt see the ping on this one. i think we have enough to proceed with this bootstrapper using cloudinit, let's go 🚀

**Comment by mhmxs** [comment]
@luthermonson One more question. The bootstrap controller is located in the `internal` package of rke2 provider. Import won't work :( I can see 4 different ways to go:

1. Use bootstrap provider as a dependency like as a separated deployment, and find alternatives to apply our customizations somehow.
2. Deploy the bootstrap provider within our provider, and find alternatives to apply our customizations somehow.
3. Sync original source code into our repo (it needs some workaround, 3 easy steps: clone, copy internal, rename imports) and we can do any customization.
4. Ask rke2 team to make package external and we can do any customization.

All requires some effort, so i don't want to waste any time on doing the wrong thing.

**Comment by richardcase** [comment]
@luthermonson @mhmxs - i see no issues in moving the controllers to an external package.  I'd be happy to approve the change.

**Comment by mhmxs** [comment]
@luthermonson @richardcase I dag into deeper into the codebase of the rke2 providers, and there is an issue to talk about. So there is a direct connection between bootstrap and controlplane controllers in rke2. If we would like to reuse the provider as it is, we have to create a few rke2 specific custom resources. One of them is watched by a rke2 controller. That means customer couldn't deploy both linode and rke2 providers in the same time without difficulties. The options I see to fix this:

 - Ask customer to deploy rke2 provider as a dependency, and we solve our customization stuff only by configuration. But that means customers face with rke2 objects, and they need to know how to setup a capi.Cluster object with this mixed linode+rke2 environment.
 - Create rke2 resources in the background (in the namespace of our provider, so hidden from other workloads on the cluster) with pause annotation, so rke2 controller would skip reconciliation. And we could sync state back to linode provider's objects. The main benefit of this is we would have our own Linode* custom resources, but rke2 is not totally hidden from the customer (objects in our namespace).
 - Embed rke2 controller into linode provider, and give a fake Kube/rest client to the controller. In this way we can create rke2 specific objects in memory, so we would have our own Linode* custom resources, and rke2 is totally hidden from the customer.
 - Add 3 extra `sed`s to rke2 bootstrap internal to external converter to fit codebase into our provider.
 - Rewrite rke2 bootstrap to linode and start maintaining it independently in our repo.
 - Monkey patching :D 

What do you suggest?

**Comment by richardcase** [comment]
I think i'm missing the wider context. 

@mhmxs @luthermonson shall we jump on a call to discuss this issue?

**Comment by luthermonson** [comment]
@richardcase @mhmxs sorry for the delay. we can do a call next week. you're both EMEA, I think I'm about -8hrs on both of you so how does 4PM UTC on Tuesday Jan 16th?
